### ISSUE TITLE
What is `PauliI` rotation?

### ISSUE THREAD

**Issue by kuzminrobin** [MicrosoftDocs/quantum-docs#149]
[This page](https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/standard/prelude) refers to the `PauliI` rotation, but neither [that page](https://docs.microsoft.com/en-us/azure/quantum/user-guide/libraries/standard/prelude) nor [this one](https://docs.microsoft.com/en-us/azure/quantum/concepts-the-qubit#single-qubit-operations) illustrates what the `PauliI` rotation is. Would be nice to see/know what the `PauliI` rotation is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67925f09-12ae-c945-18be-22269a9bd81d
* Version Independent ID: d92a8082-ae6e-6f68-7337-19ded85dedba
* Content: [The qubit in quantum computing - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/concepts-the-qubit#single-qubit-operations)
* Content Source: [articles/concepts-the-qubit.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/concepts-the-qubit.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **v-benbra**

**Comment by cgranade** [comment]
As with other Pauli rotations (see https://docs.microsoft.com/qsharp/api/qsharp/microsoft.quantum.intrinsic.r), the unitary used to simulate rotation about `PauliI` can be written as an exponential: R_I(θ) = exp(−𝑖 θ 𝟙 / 2). Using that exp(𝟙) = 𝟙, we can re-write this as a global phase, R_I(θ) = exp(−𝑖 θ / 2). Since that is a global phase, `R([PauliI], _, _)` is a no-op, but `Controlled R([PauliI, _, _)` can apply a relative phase between |0⟩ and |1⟩ on the control qubit.

**Comment by dime10** [comment]
Thank you @kuzminrobin for your feedback. As @cgranade indicated, the effect of a `PauliI` rotation is given by the definition of the `R` operation, as described in the prelude article under 'Rotations'. The note box in that section also mentions that a `PauliI` rotation only applies a global phase. Unfortunately, global phase operations cannot be as easily represented on the Bloch sphere as other rotations, since they do not modify the Bloch vector that represents the qubit state.
