### ISSUE TITLE
cd to Miniconda3\envs

### ISSUE THREAD

**Issue by i-run-knee** [MicrosoftDocs/quantum-docs#157]
This is a nit but when blindly following the instructions I could not properly activate the qsharp-env at first and then realized I should probably locate the environment first before running conda activate qsharp. 
A brief step to cd to <pathto>miniconda3\envs before the activate step may help some users unfamiliar with anaconda and virtual envs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4cc2a2b-76ba-f5a2-2eba-c2878d300fea
* Version Independent ID: 48a7a218-babc-7e50-5b4e-83c91144ea7c
* Content: [Develop with Q# and Python - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/install-python-qdk?tabs=tabid-conda)
* Content Source: [articles/install-python-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-python-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by SoniaLopezBravo** [comment]
Hello @i-run-knee ! Thank you for your feedback. If you follow the step-by-step instructions in" Installing `qsharp` Python package using conda", step 2 states that you need to open an Anaconda Prompt, not just the cmd because conda will not be recognized as a command. This step is important, as Anaconda Prompt opens in its file path and then you are ready to use the Python interpreter. To open an Anaconda Prompt, from the Start menu, search for and open “Anaconda Prompt”.

**Comment by dime10** [comment]
This is odd, since if you were able to run `conda` to install the environment, you should also be able to activate it. As far as I know, locating the environment first is not required. @i-run-knee do you know what error you were getting?

**Comment by i-run-knee** [comment]
Hi @SoniaLopezBravo , thank you for getting back to me. The second step also mentions or if you prefer open the powershell which is what I did. I was able to finally have everything working from powershell itself since I had added conda to environment path and then migrated to the location env was created (which conda by defualt creates in Miniconda/envs dir). If the prefered path is to use the Anaconda prompt, then I would suggest removing the alternative since it's not straightforward as is.

**Comment by i-run-knee** [comment]
Hi @dime10 
This is the result when follwoing the steps as is exactly
![image](https://user-images.githubusercontent.com/64760025/116740868-70fb8b80-a9aa-11eb-862b-fde5ca54fc64.png)

**Comment by dime10** [comment]
Thank you for providing the error message @i-run-knee . I think this related to the Conda-PowerShell issue I mentioned in your other issue (#158). If the environment activated correctly, its name should appear in parenthesis in front of the shell prompt, which I don't see in your screenshot. I can reproduce this same issue.

Did you execute the `conda init powershell` command before trying to activate an environment in PowerShell?

If you navigate to `Miniconda3\envs` first, you are then able to run the `conda activate qsharp-env` command successfully (i.e. the environment name is shown in front of your prompt)? This I was not able to reproduce on my side.

**Comment by SoniaLopezBravo** [comment]
@i-run-knee 

Before anything else, check that you have the latest miniconda and PowerShell version, and be sure that you are using PowerShell(x86) or PowerShell 7 (x64).

If you are using Powershell you first need to init Conda by executing `conda init powershell`, otherwise `conda` would not be recognized as a cmdlet. To do that, locate and run the `conda-hook.ps1` file in your Anaconda or Miniconda folder. For example in my case I did:
`PS  C:\Users\username> cd C:\Users\username\Anaconda3\shell\condabin`
`PS C:\Users\username\Anaconda3\shell\condabin> .\conda-hook.ps1`
`PS C:\Users\username\Anaconda3\shell\condabin> conda init powershell`

Now you should see that you are in "base" environment and `conda` is now a valid cmdlet. You can create and activate your `qsharp-env`. 

You don't need to locate `miniconda3\env` but the `miniconda3\shell\condabin`, I don't know if this was the issue you were running to in the first place. This is an extra step that you don't need to take if you are using an Anaconda Prompt.

Additionally,  you don't close the shell, it might seems that you need to set this location every time, but if you close and reopen the shell, you should see something like this:

`(base) PS C:\Users\username>`

That is, "base" conda environment is already activated and you can run `conda activate qsharp-env`. Note that you are in the root path and you don't need to set any other location. 

Let us know if the issue was fixed.

**Comment by i-run-knee** [comment]
Hi, thanks, yes I am able to activate the envs following @dime10 's suggestion
