### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by anpaz** [MicrosoftDocs/quantum-docs#17]
In Linux, if the user had to install .NET Core, they must first logout and log back in before they can install `iqsharp`.
This is a known limitation in Linux: https://github.com/dotnet/cli/issues/8368
For other platforms, the user must at least start a new console window so the PATH variable gets updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa31568-61b3-cb7f-bda5-d88134449907
* Version Independent ID: b44cf531-1535-cc4c-873f-d33b7f887e11
* Content: [Learn how to install the Microsoft Quantum Development Kit (QDK) - Microsoft Quantum](https://docs.microsoft.com/en-us/quantum/install-guide/?view=qsharp-preview)
* Content Source: [articles/install-guide/index.md](https://github.com/MicrosoftDocs/quantum-docs-pr/blob/live/articles/install-guide/index.md)
* Product: **quantum**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by dime10** [comment]
You should be able to install iqsharp (or other tools) just fine, however running the tool (in this case to install the kernel) might indeed require logging out/in. The CLI warns the user about this, stating "Since you just installed the .NET Core SDK, you will need to logout or restart your session before running the tool you installed."

The _Note_ in the [Q# with Python (CLI)](https://docs.microsoft.com/en-us/azure/quantum/install-python-qdk?tabs=tabid-dotnetcli) section also has instructions to circumvent this, by specifying the path to the dotnet-iqsharp directly.
However, the instructions about restarting the terminal may only apply to Windows I believe, so we could make this clearer/more platform specific and add the logout procedure for Linux.

Additionally, I encountered the same error as @linearstream and had install the kernel in user mode (dotnet iqsharp install --user).
