### ISSUE TITLE
Optimization "How-to" guide references Quantum Computing and Q#

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#303]
In the optimization "how-to guide" for submitting a job, there are examples for using quantum computing with Q# and Python, however the Azure Quantum optimization offering doesn't target QC currently. I think we should remove these or replace with Azure Quantum optimization equivalents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bea049b-35e3-72ed-ea80-71a7968e7e12
* Version Independent ID: ec461880-8ee8-d258-7283-62bfd65ca1a7
* Content: [Submit jobs to Azure Quantum - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/how-to-submit-jobs?tabs=tabid-python)
* Content Source: [articles/how-to-submit-jobs.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/how-to-submit-jobs.md)
* Service: **azure-quantum**
* Sub-service: **core**
* GitHub Login: @Bradben
* Microsoft Alias: **v-benbra**

**Comment by Bradben** [comment]
Thanks for catching that, Frances. That was a copy/paste error on my part during the TOC restructure. However, since you brought it up, can the examples and content there be easily reworked for Optimization or is it more complex than that? We could repurpose the content into a new topic "Submitting Optimization jobs" and "Submitting QC jobs", for example.

**Comment by Bradben** [comment]
Work item created in DevOps: [1865777](https://dev.azure.com/mseng/TechnicalContent/_queries/edit/1865777/?triage=true)
