### ISSUE TITLE
Provide a page on measurements in the Q# guide

### ISSUE THREAD

**Issue by frtibble** [MicrosoftDocs/quantum-docs#368]
This is a suggestion/docs enhancement request based on the following feedback:

> I am currently working on the kata RandomNumberGeneration, which is simple. Except I do not understand how do cast my measurement into the types needed. In this case result to int
> operation RandomBit () : Int {
>     use q = Qubit();
>     H(q);
>  return M(q)==0  ? 0 | 1; //this part does not work
> }
>  
> There is little information in the documentation online. Could you please provide more explanation on the coding part of measurements, or coding snippets how to use measurements and process the results?

Currently we have docs on how to do measurements in a few places:
- [API reference](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.intrinsic.m): This provides docs about the input/output but no code examples of how to use the `M` operation.
- [Q# programs](https://docs.microsoft.com/en-us/azure/quantum/user-guide/programs): This has a code snippet, though it's maybe not obvious to find if you were searching for `M` or measurements in general.
- [Result arrays](https://docs.microsoft.com/en-us/azure/quantum/tutorial-qdk-qubit-level-program?tabs=tabid-cmdline): This tutorial talks about result arrays with type `Result[]`, though may also be hard to find separately.

So a suggestion (based on the above) would be to add a page to the Q# docs which summarises the different ways measurements can be done in Q#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1310be9-5ecf-80aa-ef1c-b04c1159260a
* Version Independent ID: 3d2af32f-4b6a-9757-0598-df62b503c099
* Content: [Q# programming language introduction - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/user-guide/programs)
* Content Source: [articles/user-guide/programs.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/user-guide/programs.md)
* Service: **azure-quantum**
* Sub-service: **qsharp-guide**
* GitHub Login: @beheim
* Microsoft Alias: **beheim**

**Comment by SoniaLopezBravo** [comment]
The thing is that there are not different ways to do a quantum measurement. The concept of measurement in quantum computing and in Q# is "simple", to measure is to make a projection on the Pauli basis. In this [Pauli measurements] (https://docs.microsoft.com/en-us/azure/quantum/concepts-pauli-measurements) the main ideas of this concept are collected. 

Since in Q# measuring can be seen as just another operation, instead of writing a page what we can do to facilitate access to the M operation is to add a measurement section [here](https://docs.microsoft.com/en-us/azure/quantum/user-guide/programs),and enable links to Pauli measurements article and to the sample.

**Comment by SoniaLopezBravo** [comment]
Just created a [work item](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1937764) for this.
