### ISSUE TITLE
Clarification on HQC (Honeywell Quantum Credit) formula

### ISSUE THREAD

**Issue by singular-value** [MicrosoftDocs/quantum-docs#52]
Hello, I'm seeking clarification on the formula for HQC:

<img src="https://user-images.githubusercontent.com/3976048/109352632-bed80400-7840-11eb-9cc5-50ba24fd1c37.png" width="500">

- What is the multiplier C? Is it the counts? That's what would make sense to me conceptually, but just wanted to make sure.
- It looks like any task on Honeywell would cost at least 5 HQC. Is this right? HQC are priced at $6.40 each, so that means each task would cost at least $32, which seems very steep. 
  - Is the "5 + " supposed to be divided by the 5000 as well? (If so, there should be another set of parentheses spanning the full numerator).

Thanks,
Pranav

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6982849f-649b-c518-45b9-daaa0b0f8cf1
* Version Independent ID: 925492ad-c390-4c2a-2485-4190ca61f8c7
* Content: [Honeywell provider - Azure Quantum ](https://docs.microsoft.com/en-us/azure/quantum/provider-honeywell)
* Content Source: [articles/provider-honeywell.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/provider-honeywell.md)
* Service: **azure-quantum**
* Sub-service: **computing**
* GitHub Login: @Mobius5150
* Microsoft Alias: **mblouin**

**Comment by geduardo** [comment]
@Mobius5150

**Comment by Mobius5150** [comment]
Hello @singular-value, thank you for reporting this issue!

I can confirm that `C` is the shot count. I will submit an update to the documentation. 

Otherwise, you are correct that the minimum cost of a job as set by Honeywell is 5 HQC. If you have further questions about Honeywell pricing you may contact them using the information on this document: https://docs.microsoft.com/en-us/azure/quantum/provider-support-honeywell

**Comment by singular-value** [comment]
Thanks for the clarification.
