### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by johnehutchinson** [MicrosoftDocs/quantum-docs#543]
[Enter feedback here]
"Use a local development environment -> Configuration -> Set up a Q# standalone or .NET environment"
followed by:
"Use a local development environment -> Configuration -> Set up a Q# Python environment"
is confusing for a beginner (like me) 
 
The second subsection is essentially a subset of the first subsection.
I suggest 
1) changing the order of the two subsections
2) add an explanatory note at the beginning of each subsection

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ab9f40-b7d0-a0b3-03b8-07af34bf1bbc
* Version Independent ID: c51474b6-0c8d-c78b-294a-184ddbcd1bcf
* Content: [Set up a Q# standalone environment - Azure Quantum ](https://docs.microsoft.com/en-au/azure/quantum/install-command-line-qdk)
* Content Source: [articles/install-command-line-qdk.md](https://github.com/MicrosoftDocs/quantum-docs/blob/main/articles/install-command-line-qdk.md)
* Service: **azure-quantum**
* Sub-service: **qdk**
* GitHub Login: @Bradben
* Microsoft Alias: **brbenefield**

**Comment by SoniaLopezBravo** [comment]
Hi @johnehutchinson ! Thanks for your submission. We are currently working on a new article to clarify these questions that usually arise regarding the ways of running a Q# program and local development. 

In the meantime, I will try to clear your doubts.

Please note that the introduction to these 2 topics can be found here [Configure your local environment](https://docs.microsoft.com/en-au/azure/quantum/install-overview-qdk), the first section under  "Use a local development environment" node. 

A Q# program can be run as standalone or can be invoked using a host program with Python, C# or F#. 
In order to develop Q# + Python programs, one needs to install `qsharp` Python package, so that is the purpose of [Set up a Q# + Python environment](https://docs.microsoft.com/en-au/azure/quantum/install-python-qdk?tabs=tabid-conda).

To run as standalone or use .NET CLI, no extra package is needed.

**Comment by johnehutchinson** [comment]
Thanks Sonia for the prompt reply!

I was really just pointing out some instructions I initially found somewhat confusing.

I have in fact eventually installed qsharp, using anaconda navigator, as an anaconda environment, on my university machine (mac).  It is running well, I have tested it on some of the quantum katas.

However, on my home machine, a macbook pro, the "same" qsharp environment installed in the same manner,  kills the kernel every time.  I'll try to clone the university copy of the environment, bring that home, and see if it still works.  (At guess I'll have a better chance than if trying to clone a single qubit 😀 )

John

**Comment by SoniaLopezBravo** [comment]
Closing this issue as it had been addressed in the latest changes of the TOC. New article is https://learn.microsoft.com/en-au/azure/quantum/install-overview-qdk?tabs=tabid-vscode%2Ctabid-conda
